import type {
  Article,
  Banner,
  CalendarItem,
  CmsFeature,
  DeskQueueItem,
  EditorialEvent,
  HomepageSlot,
  ReporterMetric,
} from './definitions';

export const articles: Article[] = [
  {
    id: 'art_001',
    title: '지역 의료 인프라 확충안, 예산 심의 첫 관문 통과',
    slug: 'local-healthcare-budget-review',
    summary:
      '시의회 예산소위가 지역 응급의료센터 증설안을 조건부 통과시키며 후속 조정에 들어갔다.',
    section: '사회',
    desk: 'online',
    status: 'desk_review',
    author: '김민서',
    editor: '박준영',
    sourceReleaseTitle: '시 보건국 2026 의료 인프라 확충 보도자료',
    similarityScore: 0.71,
    seoKeywords: ['지역 의료', '응급의료센터', '예산 심의'],
    views: 18420,
    likes: 326,
    readDepth: 68,
    reporterAwarenessScore: 82,
    updatedAt: '2026-06-13T09:20:00+09:00',
  },
  {
    id: 'art_002',
    title: '대학가 창업 보육센터 입주 경쟁률 4.2대 1',
    slug: 'campus-startup-incubator-competition',
    summary:
      '기술 기반 초기 창업팀이 늘며 지역 대학 창업 보육센터의 평균 입주 경쟁률이 상승했다.',
    section: '경제',
    desk: 'print',
    status: 'scheduled',
    author: '이도현',
    editor: '최유진',
    seoKeywords: ['대학 창업', '보육센터', '지역 경제'],
    views: 12110,
    likes: 204,
    readDepth: 74,
    reporterAwarenessScore: 77,
    scheduledAt: '2026-06-13T18:00:00+09:00',
    updatedAt: '2026-06-13T08:05:00+09:00',
  },
  {
    id: 'art_003',
    title: '주말 문화행사, 도심 광장 중심으로 확대',
    slug: 'weekend-culture-events-expand',
    summary:
      '문화재단은 가족 단위 방문객을 겨냥해 공연과 체험 프로그램을 도심 광장에 집중 배치한다.',
    section: '문화',
    desk: 'online',
    status: 'published',
    author: '정하린',
    seoKeywords: ['주말 행사', '문화재단', '도심 광장'],
    views: 26880,
    likes: 510,
    readDepth: 61,
    reporterAwarenessScore: 88,
    publishedAt: '2026-06-12T16:30:00+09:00',
    updatedAt: '2026-06-12T17:05:00+09:00',
  },
  {
    id: 'art_004',
    title: '교육청, 디지털 교과서 시범학교 추가 선정',
    slug: 'digital-textbook-pilot-schools',
    summary:
      '디지털 교과서 시범학교가 초중고 전 학년으로 확대되며 교사 연수 일정도 함께 조정된다.',
    section: '교육',
    desk: 'video',
    status: 'copyediting',
    author: '한지우',
    editor: '윤서진',
    sourceReleaseTitle: '교육청 디지털 교육 전환 계획',
    similarityScore: 0.64,
    seoKeywords: ['디지털 교과서', '시범학교', '교육청'],
    views: 9340,
    likes: 142,
    readDepth: 57,
    reporterAwarenessScore: 69,
    updatedAt: '2026-06-13T10:10:00+09:00',
  },
];

export const banners: Banner[] = [
  {
    id: 'ban_001',
    title: '여름 기획전 상단 배너',
    placement: 'top',
    imageUrl: '/opengraph-image.png',
    linkUrl: '/promo/summer',
    startsAt: '2026-06-13T00:00:00+09:00',
    endsAt: '2026-06-30T23:59:00+09:00',
    isActive: true,
    sortOrder: 1,
    ownerRole: 'ad_manager',
  },
  {
    id: 'ban_002',
    title: '지역 행사 사이드 배너',
    placement: 'sidebar',
    imageUrl: '/hero-mobile.png',
    linkUrl: '/events',
    startsAt: '2026-06-10T00:00:00+09:00',
    endsAt: '2026-06-20T23:59:00+09:00',
    isActive: true,
    sortOrder: 2,
    ownerRole: 'event_manager',
  },
];

export const events: EditorialEvent[] = [
  {
    id: 'evt_001',
    title: '시장 취임 2주년 기자간담회',
    date: '2026-06-14T10:00:00+09:00',
    location: '시청 브리핑룸',
    description: '정책 성과와 하반기 시정 방향 발표',
    isPublished: true,
    calendarSynced: true,
  },
  {
    id: 'evt_002',
    title: '지역 대학 창업 박람회',
    date: '2026-06-15T13:00:00+09:00',
    location: '컨벤션센터 2홀',
    description: '창업팀 부스 취재 및 영상 인터뷰',
    isPublished: false,
    calendarSynced: false,
  },
  {
    id: 'evt_003',
    title: '문화재단 주말 공연 리허설',
    date: '2026-06-13T19:30:00+09:00',
    location: '도심 광장',
    description: '공연 현장 스케치 및 포토 기사 준비',
    isPublished: true,
    calendarSynced: true,
  },
];

export const homepageSlots: HomepageSlot[] = [
  {
    id: 'slot_001',
    section: 'lead',
    label: '메인 리드',
    articleId: 'art_001',
    articleTitle: '지역 의료 인프라 확충안, 예산 심의 첫 관문 통과',
    position: 1,
    isVisible: true,
  },
  {
    id: 'slot_002',
    section: 'top_grid',
    label: '상단 2열',
    articleId: 'art_003',
    articleTitle: '주말 문화행사, 도심 광장 중심으로 확대',
    position: 2,
    isVisible: true,
  },
  {
    id: 'slot_003',
    section: 'latest',
    label: '최신 뉴스',
    articleId: 'art_002',
    articleTitle: '대학가 창업 보육센터 입주 경쟁률 4.2대 1',
    position: 1,
    isVisible: true,
  },
  {
    id: 'slot_004',
    section: 'feature',
    label: '기획 기사',
    articleId: 'art_004',
    articleTitle: '교육청, 디지털 교과서 시범학교 추가 선정',
    position: 1,
    isVisible: false,
  },
];

export const deskQueue: DeskQueueItem[] = [
  {
    id: 'desk_001',
    desk: 'online',
    title: '의료 인프라 예산 심의 속보',
    owner: '김민서',
    status: 'desk_review',
    deadline: '2026-06-13T11:30:00+09:00',
    priority: 'urgent',
  },
  {
    id: 'desk_002',
    desk: 'print',
    title: '창업 보육센터 지면 3단 기사',
    owner: '이도현',
    status: 'scheduled',
    deadline: '2026-06-13T17:00:00+09:00',
    priority: 'high',
  },
  {
    id: 'desk_003',
    desk: 'video',
    title: '디지털 교과서 화상 데스크 확인',
    owner: '한지우',
    status: 'copyediting',
    deadline: '2026-06-13T15:00:00+09:00',
    priority: 'normal',
  },
];

export const calendarItems: CalendarItem[] = [
  {
    id: 'cal_001',
    title: '시장 기자간담회 현장 취재',
    startsAt: '2026-06-14T09:30:00+09:00',
    endsAt: '2026-06-14T11:30:00+09:00',
    owner: '정치사회팀',
    type: 'coverage',
    googleEventId: 'google_evt_market_2nd',
  },
  {
    id: 'cal_002',
    title: '대학 창업팀 인터뷰',
    startsAt: '2026-06-15T14:00:00+09:00',
    endsAt: '2026-06-15T15:00:00+09:00',
    owner: '경제팀',
    type: 'interview',
  },
  {
    id: 'cal_003',
    title: '주말판 마감회의',
    startsAt: '2026-06-13T16:00:00+09:00',
    endsAt: '2026-06-13T16:40:00+09:00',
    owner: '편집국',
    type: 'meeting',
    googleEventId: 'google_evt_weekend_close',
  },
];

export const reporterMetrics: ReporterMetric[] = [
  {
    reporter: '정하린',
    beat: '문화',
    articles: 18,
    views: 214800,
    likes: 4210,
    avgReadDepth: 66,
    awarenessScore: 91,
  },
  {
    reporter: '김민서',
    beat: '사회',
    articles: 22,
    views: 198400,
    likes: 3560,
    avgReadDepth: 71,
    awarenessScore: 86,
  },
  {
    reporter: '이도현',
    beat: '경제',
    articles: 14,
    views: 142200,
    likes: 2380,
    avgReadDepth: 74,
    awarenessScore: 79,
  },
  {
    reporter: '한지우',
    beat: '교육',
    articles: 11,
    views: 93400,
    likes: 1510,
    avgReadDepth: 58,
    awarenessScore: 68,
  },
];

export const cmsFeatures: CmsFeature[] = [
  {
    id: 'feat_auth',
    title: '관리자 로그인과 RBAC',
    area: '권한',
    decision: 'build',
    priority: 'MVP',
    rationale: '배너, 기사, 이벤트, 통계 접근을 역할별로 분리해야 운영 사고를 줄일 수 있습니다.',
  },
  {
    id: 'feat_article_ai',
    title: '보도자료 초안 생성과 유사도 측정',
    area: 'AI 편집',
    decision: 'build',
    priority: 'MVP',
    rationale: '초안 속도는 높이되 원문 의존도가 과도한 기사를 사전에 탐지합니다.',
  },
  {
    id: 'feat_seo',
    title: 'SEO 제목, 설명, 키워드 추천',
    area: '검색',
    decision: 'build',
    priority: 'MVP',
    rationale: 'NewsArticle 구조화 데이터와 메타 정보를 기사 작성 단계에서 함께 관리합니다.',
  },
  {
    id: 'feat_layout',
    title: '메인 기사 순서와 위치 관리',
    area: '편집 배치',
    decision: 'build',
    priority: 'MVP',
    rationale: '메인 화면을 배포 없이 데스크가 직접 조정할 수 있어야 합니다.',
  },
  {
    id: 'feat_calendar',
    title: 'Google Calendar 일정 연동',
    area: '일정',
    decision: 'phase_2',
    priority: 'Phase 2',
    rationale: '취재 일정과 편집 마감을 외부 캘린더와 동기화합니다.',
  },
  {
    id: 'feat_print_monitor',
    title: '지면 모니터링',
    area: '지면',
    decision: 'phase_2',
    priority: 'Phase 2',
    rationale: '온라인 CMS와 지면 편집 흐름을 연결하되, 지면 시스템 연동 범위 확인이 필요합니다.',
  },
  {
    id: 'feat_video_desk',
    title: '화상 데스크',
    area: '영상',
    decision: 'phase_2',
    priority: 'Phase 2',
    rationale: '영상 원고, 썸네일, 자막 검수 워크플로우가 필요합니다.',
  },
  {
    id: 'feat_abtest',
    title: 'A/B 테스트와 개인화 추천',
    area: '성장',
    decision: 'hold',
    priority: 'Phase 3',
    rationale: '핵심 CMS 데이터와 분석 이벤트가 안정화된 뒤 도입하는 편이 좋습니다.',
  },
];
