import type { Article, Event, MembershipPlan } from './definitions';

export const PLACEHOLDER_ARTICLES: Article[] = [
  {
    id: '1',
    slug: '2026-iusm-jazz-festival-preview',
    title: '제7회 울산매일UTV 재즈 페스티벌, 올해도 한강공원서 개최',
    excerpt: '오는 9월 한강시민공원 반포지구에서 사흘간 열리는 재즈 페스티벌에 국내외 20개 팀이 참가한다.',
    content: '<p>울산매일UTV가 주최하는 제7회 재즈 페스티벌이 오는 9월 6일부터 8일까지 한강시민공원 반포지구에서 개최됩니다.</p><h2>주요 프로그램</h2><p>메인 스테이지에서는 매일 오후 5시부터 자정까지 공연이 이어지며, 소규모 재즈 세션을 즐길 수 있는 라운지 스테이지도 별도로 운영됩니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&q=80',
    category: 'culture',
    author: '이미나 기자',
    publishedAt: '2026-06-10T09:00:00+09:00',
    readTime: 4,
    tags: ['재즈', '페스티벌', '한강', '공연'],
    featured: true,
    premium: false,
  },
  {
    id: '2',
    slug: 'iusm-ceo-academy-2026-summer',
    title: 'CEO 아카데미 여름 과정 모집… "리더십과 혁신" 주제로',
    excerpt: '울산매일UTV CEO 아카데미가 7~8월 여름 과정 참가자를 모집한다. 강남 소재 교육장에서 매주 화요일 저녁 진행.',
    content: '<p>울산매일UTV가 운영하는 CEO 아카데미가 2026년 여름 과정 참가자를 모집합니다.</p><h2>커리큘럼</h2><p>1주차부터 4주차까지는 리더십 이론과 케이스 스터디를 중심으로, 5주차 이후에는 실전 프로젝트와 네트워킹을 중심으로 구성됩니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    category: 'business',
    author: '박준혁 기자',
    publishedAt: '2026-06-09T14:30:00+09:00',
    readTime: 3,
    tags: ['CEO', '아카데미', '리더십', '비즈니스'],
    featured: false,
    premium: false,
  },
  {
    id: '3',
    slug: 'seoul-marathon-2026-results',
    title: '서울 국제 마라톤 2026, 에티오피아 선수 세계신기록 수립',
    excerpt: '제32회 서울 국제 마라톤에서 에티오피아의 아베베 선수가 2시간 0분 12초로 세계신기록을 세웠다.',
    content: '<p>지난 주말 여의도 한강공원 일대에서 열린 제32회 서울 국제 마라톤에서 역사적인 순간이 탄생했습니다.</p><p>에티오피아의 기디 아베베 선수가 2시간 0분 12초의 기록으로 결승선을 통과하며 기존 세계기록을 1분 이상 단축시켰습니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1594882645126-14020914d58d?w=800&q=80',
    category: 'sports',
    author: '최성훈 기자',
    publishedAt: '2026-06-08T18:00:00+09:00',
    readTime: 5,
    tags: ['마라톤', '서울', '육상', '세계기록'],
    featured: true,
    premium: false,
  },
  {
    id: '4',
    slug: 'youth-entrepreneurship-fair-2026',
    title: '청년 창업 박람회 7월 개최… 스타트업 300개사 참가 예정',
    excerpt: '울산매일UTV 주최 청년 창업 박람회가 7월 코엑스에서 열린다. 투자자 매칭 프로그램도 병행 운영.',
    content: '<p>울산매일UTV가 주최하는 2026 청년 창업 박람회가 오는 7월 15일부터 17일까지 코엑스 전시관에서 개최됩니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80',
    category: 'startup',
    author: '김지수 기자',
    publishedAt: '2026-06-07T10:00:00+09:00',
    readTime: 4,
    tags: ['청년창업', '박람회', '스타트업', '투자'],
    featured: false,
    premium: false,
  },
  {
    id: '5',
    slug: 'iusm-literary-award-2026-winners',
    title: '울산매일UTV 문학상 수상작 발표… 소설 부문 첫 10대 수상자 탄생',
    excerpt: '제15회 울산매일UTV 문학상에서 18세 고등학생이 소설 부문 대상을 수상해 문단의 주목을 받았다.',
    content: '<p>제15회 울산매일UTV 문학상 수상자가 발표됐습니다. 소설 부문에서는 서울 소재 고등학교 3학년 김연서 씨(18)가 대상을 수상해 이목을 집중시켰습니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    category: 'humanities',
    author: '송혜원 기자',
    publishedAt: '2026-06-06T16:00:00+09:00',
    readTime: 6,
    tags: ['문학상', '수상', '소설', '청년작가'],
    featured: false,
    premium: false,
  },
  {
    id: '6',
    slug: 'korean-startup-ecosystem-report-2026',
    title: '2026 한국 스타트업 생태계 리포트: 투자 위축 속 AI 분야 강세',
    excerpt: '전반적인 투자 규모는 감소했지만 AI, 바이오 분야는 오히려 증가. IUSM 리서치팀 분석 보고서.',
    content: '<p>IUSM 리서치팀이 발표한 2026 상반기 한국 스타트업 생태계 리포트에 따르면, 전체 투자 규모는 전년 동기 대비 15% 감소했지만 AI 분야는 32% 증가했습니다.</p>',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    category: 'startup',
    author: '정다은 기자',
    publishedAt: '2026-06-05T11:00:00+09:00',
    readTime: 8,
    tags: ['스타트업', '투자', 'AI', '리포트'],
    featured: false,
    premium: true,
  },
];

export const PLACEHOLDER_EVENTS: Event[] = [
  {
    id: '1',
    slug: 'iusm-jazz-festival-2026',
    title: '제7회 울산매일UTV 재즈 페스티벌',
    description: '한강공원에서 사흘간 펼쳐지는 국내 최대 재즈 페스티벌. 국내외 20개 팀이 3개 무대에서 공연합니다.',
    thumbnail: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&q=80',
    heroImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80',
    type: 'festival',
    status: 'upcoming',
    startDate: '2026-09-06',
    endDate: '2026-09-08',
    location: '한강시민공원 반포지구',
    organizer: 'IUSM',
    price: 35000,
    maxCapacity: 5000,
    currentRegistrations: 2341,
    tags: ['재즈', '음악', '페스티벌', '한강'],
    featured: true,
    registrationDeadline: '2026-08-31',
  },
  {
    id: '2',
    slug: 'seoul-marathon-2026',
    title: '제32회 서울 국제 마라톤',
    description: '여의도 한강공원을 출발점으로 하는 풀코스 마라톤. 아마추어 10km 레이스도 동시 진행됩니다.',
    thumbnail: 'https://images.unsplash.com/photo-1594882645126-14020914d58d?w=600&q=80',
    type: 'marathon',
    status: 'ended',
    startDate: '2026-06-01',
    endDate: '2026-06-01',
    location: '여의도 한강공원',
    organizer: 'IUSM 스포츠',
    price: 50000,
    maxCapacity: 10000,
    currentRegistrations: 9823,
    tags: ['마라톤', '달리기', '스포츠', '한강'],
    featured: false,
  },
  {
    id: '3',
    slug: 'youth-startup-fair-2026',
    title: '2026 청년 창업 박람회',
    description: '300개 스타트업이 한 자리에 모이는 국내 최대 청년 창업 박람회. 투자자 매칭, IR 데이 포함.',
    thumbnail: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=600&q=80',
    type: 'fair',
    status: 'upcoming',
    startDate: '2026-07-15',
    endDate: '2026-07-17',
    location: '코엑스 전시관 B홀',
    organizer: 'IUSM 스타트업',
    price: null,
    maxCapacity: 20000,
    currentRegistrations: 8500,
    tags: ['창업', '스타트업', '박람회', '코엑스'],
    featured: true,
    registrationDeadline: '2026-07-10',
  },
  {
    id: '4',
    slug: 'ceo-academy-summer-2026',
    title: 'CEO 아카데미 2026 여름 과정',
    description: '현직 CEO와 전문가가 함께하는 8주 집중 리더십 과정. 매주 화요일 저녁, 강남 소재 교육장.',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80',
    type: 'academy',
    status: 'upcoming',
    startDate: '2026-07-01',
    endDate: '2026-08-19',
    location: '강남구 테헤란로 IUSM 교육센터',
    organizer: 'IUSM 비즈니스',
    price: 1200000,
    maxCapacity: 30,
    currentRegistrations: 18,
    tags: ['CEO', '아카데미', '리더십', '교육'],
    featured: true,
    registrationDeadline: '2026-06-25',
  },
  {
    id: '5',
    slug: 'iusm-golf-tournament-2026',
    title: '2026 IUSM 골프 대회',
    description: '기업인과 스포츠 팬이 함께하는 연례 골프 대회. 18홀 스트로크 플레이, 단체전 포함.',
    thumbnail: 'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=600&q=80',
    type: 'golf',
    status: 'upcoming',
    startDate: '2026-10-12',
    endDate: '2026-10-12',
    location: '경기도 용인 블루헤런 골프클럽',
    organizer: 'IUSM 스포츠',
    price: 300000,
    maxCapacity: 200,
    currentRegistrations: 45,
    tags: ['골프', '대회', '기업인', '스포츠'],
    featured: false,
    registrationDeadline: '2026-09-30',
  },
  {
    id: '6',
    slug: 'iusm-literary-award-2026',
    title: '제15회 울산매일UTV 문학상 시상식',
    description: '소설, 시, 수필 3개 부문 수상자를 시상하는 연례 문학상 시상식.',
    thumbnail: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80',
    type: 'award',
    status: 'ended',
    startDate: '2026-06-05',
    endDate: '2026-06-05',
    location: '세종문화회관 대강당',
    organizer: 'IUSM 인문학',
    price: null,
    maxCapacity: 500,
    currentRegistrations: 500,
    tags: ['문학상', '시상식', '수상', '문학'],
    featured: false,
  },
];

export const PLACEHOLDER_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'individual-monthly',
    name: '개인 월간',
    tier: 'individual',
    price: 9900,
    period: 'monthly',
    features: [
      '모든 프리미엄 기사 무제한 열람',
      '뉴스레터 매주 발송',
      '이벤트 얼리버드 신청 우선권',
      '댓글 및 커뮤니티 참여',
      '광고 없는 클린 읽기 환경',
    ],
    highlighted: false,
  },
  {
    id: 'individual-yearly',
    name: '개인 연간',
    tier: 'individual',
    price: 89000,
    period: 'yearly',
    features: [
      '모든 프리미엄 기사 무제한 열람',
      '뉴스레터 매주 발송',
      '이벤트 얼리버드 신청 우선권',
      '댓글 및 커뮤니티 참여',
      '광고 없는 클린 읽기 환경',
      '연간 리포트 PDF 제공',
      '월간 대비 25% 할인',
    ],
    highlighted: true,
  },
  {
    id: 'corporate',
    name: '기업/단체',
    tier: 'corporate',
    price: 590000,
    period: 'yearly',
    features: [
      '최대 10인 계정 공유',
      '모든 프리미엄 콘텐츠 접근',
      'CEO 아카데미 10% 할인',
      '이벤트 스폰서 우선 협의',
      '기업 로고 미디어 노출',
      '분기별 리서치 리포트',
      '전담 담당자 배정',
    ],
    highlighted: false,
  },
];

export const BREAKING_NEWS = [
  '서울 국제 마라톤 2026, 에티오피아 선수 세계신기록 수립',
  'CEO 아카데미 여름 과정 모집 마감 임박 — 잔여석 12석',
  '제7회 재즈 페스티벌 라인업 공개, 해외 유명 뮤지션 3팀 확정',
  '청년 창업 박람회 사전 등록자 8,500명 돌파',
];
